//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Backpack_inventoryuisetting_asset
    {
        public const string BundleName = "backpack_inventoryuisetting_asset";
        public const string BACKPACK_INVENTORYUISETTING = "backpack_inventoryuisetting";
    }
    public class Equipment_inventoryuisetting_asset
    {
        public const string BundleName = "equipment_inventoryuisetting_asset";
        public const string EQUIPMENT_INVENTORYUISETTING = "equipment_inventoryuisetting";
    }
    public class Itempickerprefab_prefab
    {
        public const string BundleName = "itempickerprefab_prefab";
        public const string ITEMPICKERPREFAB = "itempickerprefab";
    }
    public class Minimalist_cartoon_animal_png
    {
        public const string BundleName = "minimalist cartoon animal_png";
        public const string MINIMALIST_CARTOON_ANIMAL = "minimalist cartoon animal";
    }
    public class New_item_database_asset
    {
        public const string BundleName = "new item database_asset";
        public const string NEW_ITEM_DATABASE = "new item database";
    }
    public class Player_prefab
    {
        public const string BundleName = "player_prefab";
        public const string PLAYER = "player";
    }
    public class Shortcutinventory_prefab
    {
        public const string BundleName = "shortcutinventory_prefab";
        public const string INVENTORYUIPANEL = "inventoryuipanel";
    }
    public class Shoutcut_inventoryuisetting_asset
    {
        public const string BundleName = "shoutcut_inventoryuisetting_asset";
        public const string SHOUTCUT_INVENTORYUISETTING = "shoutcut_inventoryuisetting";
    }
    public class Stack_prefab
    {
        public const string BundleName = "stack_prefab";
        public const string STACK = "stack";
    }
}
