//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Minimalist_cartoon_animal_png
    {
        public const string BundleName = "minimalist cartoon animal_png";
        public const string MINIMALIST_CARTOON_ANIMAL = "minimalist cartoon animal";
    }
    public class Player_prefab
    {
        public const string BundleName = "player_prefab";
        public const string PLAYER = "player";
    }
    public class Shortcutinventory_prefab
    {
        public const string BundleName = "shortcutinventory_prefab";
        public const string SHORTCUTINVENTORY = "shortcutinventory";
    }
}
